name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Lint with flake8
      run: |
        flake8 gcp_secrets_manager tests --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 gcp_secrets_manager tests --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Format check with black
      run: |
        black --check gcp_secrets_manager tests
    
    - name: Sort imports check with isort
      run: |
        isort --check-only gcp_secrets_manager tests
    
    - name: Type check with mypy
      run: |
        mypy gcp_secrets_manager
    
    - name: Test with pytest
      run: |
        pytest tests/ -v --cov=gcp_secrets_manager --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true